#!/bin/zsh -e
 
cd $(dirname $0)
 
if [[ $# -lt 2 || $# -gt 3 ]]; then
  echo "usage: $0 SRC_DIR DST_DIR [-w]"
  exit 1
fi
 
src=$1
dst=$2
doit=$3
 
if [[ $doit == -w ]]; then
  dry=
else
  dry='-n'
fi
 
rsync --archive --one-file-system --inplace --hard-links \
  --human-readable --numeric-ids --delete --delete-excluded \
  --itemize-changes --verbose --progress \
  --exclude='*~' --exclude=__pycache__ \
  --exclude-from=root.exclude \
  $src $dst $dry

if [[ $doit == -w ]]; then
	cd $dst/../
	btrfs subvolume snapshot -r current $(date +'%Y%m%d_%H:%M')
	#btrfs subvolume snapshot -r current $(date +'%Y%m%d')
fi
